/* Generated By:JavaCC: Do not edit this line. CompilerConstants.java */
package com.example.compiler_testes;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RESULT = 11;
  /** RegularExpression Id. */
  int AVALIATE = 12;
  /** RegularExpression Id. */
  int DO = 13;
  /** RegularExpression Id. */
  int THIS = 14;
  /** RegularExpression Id. */
  int BODY = 15;
  /** RegularExpression Id. */
  int DESCRIPTION = 16;
  /** RegularExpression Id. */
  int DECLARATION = 17;
  /** RegularExpression Id. */
  int TYPE = 18;
  /** RegularExpression Id. */
  int IS = 19;
  /** RegularExpression Id. */
  int CONSTANT = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int VARIABLE = 22;
  /** RegularExpression Id. */
  int DESIGNATE = 23;
  /** RegularExpression Id. */
  int AS = 24;
  /** RegularExpression Id. */
  int READ = 25;
  /** RegularExpression Id. */
  int WRITE = 26;
  /** RegularExpression Id. */
  int ALL = 27;
  /** RegularExpression Id. */
  int REPEAT = 28;
  /** RegularExpression Id. */
  int INTEGER_DEF = 29;
  /** RegularExpression Id. */
  int REAL_DEF = 30;
  /** RegularExpression Id. */
  int LITERAL_DEF = 31;
  /** RegularExpression Id. */
  int LOGIC_DEF = 32;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 33;
  /** RegularExpression Id. */
  int DIGITOS = 34;
  /** RegularExpression Id. */
  int FIM = 35;
  /** RegularExpression Id. */
  int _DIGITO = 36;
  /** RegularExpression Id. */
  int _LETRA = 37;
  /** RegularExpression Id. */
  int INTEGER = 38;
  /** RegularExpression Id. */
  int REAL = 39;
  /** RegularExpression Id. */
  int TRUE = 40;
  /** RegularExpression Id. */
  int UNTRUE = 41;
  /** RegularExpression Id. */
  int LITERAL = 42;
  /** RegularExpression Id. */
  int PLUS = 43;
  /** RegularExpression Id. */
  int MINUS = 44;
  /** RegularExpression Id. */
  int MULTIPLY = 45;
  /** RegularExpression Id. */
  int DIVIDE = 46;
  /** RegularExpression Id. */
  int POWER = 47;
  /** RegularExpression Id. */
  int MODULO = 48;
  /** RegularExpression Id. */
  int DOUBLE_MODULO = 49;
  /** RegularExpression Id. */
  int LESS_THAN = 50;
  /** RegularExpression Id. */
  int LESS_THAN_EQUAL = 51;
  /** RegularExpression Id. */
  int GREATER_THAN_EQUAL = 52;
  /** RegularExpression Id. */
  int GREATER_THAN = 53;
  /** RegularExpression Id. */
  int EQUAL = 54;
  /** RegularExpression Id. */
  int NOT_EQUAL = 55;
  /** RegularExpression Id. */
  int AND_LOGIC = 56;
  /** RegularExpression Id. */
  int OR_LOGIC = 57;
  /** RegularExpression Id. */
  int NOT_LOGIC = 58;
  /** RegularExpression Id. */
  int HASH = 59;
  /** RegularExpression Id. */
  int DOLLAR = 60;
  /** RegularExpression Id. */
  int OPEN_PAREN = 61;
  /** RegularExpression Id. */
  int CLOSE_PAREN = 62;
  /** RegularExpression Id. */
  int COMMA = 63;
  /** RegularExpression Id. */
  int DOT = 64;
  /** RegularExpression Id. */
  int COLON = 65;
  /** RegularExpression Id. */
  int SEMICOLON = 66;
  /** RegularExpression Id. */
  int S_LESS_THAN = 67;
  /** RegularExpression Id. */
  int S_GREATER_THAN = 68;
  /** RegularExpression Id. */
  int QUESTION_MARK = 69;
  /** RegularExpression Id. */
  int AT_SIGN = 70;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 71;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 72;
  /** RegularExpression Id. */
  int BACKTICK = 73;
  /** RegularExpression Id. */
  int OPEN_BRACE = 74;
  /** RegularExpression Id. */
  int CLOSE_BRACE = 75;
  /** RegularExpression Id. */
  int TILDE = 76;
  /** RegularExpression Id. */
  int EQUALS = 77;
  /** RegularExpression Id. */
  int MAIUSCULA = 78;
  /** RegularExpression Id. */
  int MINUSCULA = 79;
  /** RegularExpression Id. */
  int DIGITO = 80;
  /** RegularExpression Id. */
  int LETRA = 81;
  /** RegularExpression Id. */
  int ASCII_ASPAS = 82;
  /** RegularExpression Id. */
  int ASCII_APOSTROFO = 83;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 84;
  /** RegularExpression Id. */
  int INVALID_CONST = 85;
  /** RegularExpression Id. */
  int ERROR_INTEGER = 86;
  /** RegularExpression Id. */
  int ERROR_REAL = 87;
  /** RegularExpression Id. */
  int ERROR_LITERAL_END = 88;
  /** RegularExpression Id. */
  int ERROR_DIGITOS = 89;
  /** RegularExpression Id. */
  int ERROR__FIM = 90;
  /** RegularExpression Id. */
  int ERROR_FIM_DIGITO = 91;
  /** RegularExpression Id. */
  int ERROR__DIGITO = 92;
  /** RegularExpression Id. */
  int ERROR__LETRA = 93;
  /** RegularExpression Id. */
  int ERROR_IDENTIFICADOR = 94;
  /** RegularExpression Id. */
  int ERROR_IDENTIFICADOR_START_DIGIT = 95;
  /** RegularExpression Id. */
  int ERROR_IDENTIFICADOR_MULTIPLE_UNDERSCORES = 96;
  /** RegularExpression Id. */
  int ERROR_IDENTIFICADOR_START_LOWERCASE = 97;
  /** RegularExpression Id. */
  int ERROR_IDENTIFICADOR_END_DIGIT = 98;
  /** RegularExpression Id. */
  int ERROR_IDENTIFICADOR_START_UNDERSCORE = 99;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int singlelinecomment = 1;
  /** Lexical state. */
  int multilinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/*\"",
    "\"//\"",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"*/\"",
    "<token of kind 10>",
    "\"result\"",
    "\"avaliate\"",
    "\"do\"",
    "\"this\"",
    "\"body\"",
    "\"description\"",
    "\"declaration\"",
    "\"type\"",
    "\"is\"",
    "\"constant\"",
    "\"and\"",
    "\"variable\"",
    "\"designate\"",
    "\"as\"",
    "\"read\"",
    "\"write\"",
    "\"all\"",
    "\"repeat\"",
    "\"integer\"",
    "\"real\"",
    "\"literal\"",
    "\"logic\"",
    "<IDENTIFICADOR>",
    "<DIGITOS>",
    "<FIM>",
    "<_DIGITO>",
    "<_LETRA>",
    "<INTEGER>",
    "<REAL>",
    "\"true\"",
    "\"untrue\"",
    "<LITERAL>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"%\"",
    "\"%%\"",
    "\"<<\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>\"",
    "\"==\"",
    "\"!=\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"#\"",
    "\"$\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\";\"",
    "\"<\"",
    "\">\"",
    "\"?\"",
    "\"@\"",
    "\"[\"",
    "\"]\"",
    "\"`\"",
    "\"{\"",
    "\"}\"",
    "\"~\"",
    "\"=\"",
    "<MAIUSCULA>",
    "<MINUSCULA>",
    "<DIGITO>",
    "<LETRA>",
    "<ASCII_ASPAS>",
    "<ASCII_APOSTROFO>",
    "<INVALID_LEXICAL>",
    "<INVALID_CONST>",
    "<ERROR_INTEGER>",
    "<ERROR_REAL>",
    "<ERROR_LITERAL_END>",
    "<ERROR_DIGITOS>",
    "\"__\"",
    "<ERROR_FIM_DIGITO>",
    "<ERROR__DIGITO>",
    "<ERROR__LETRA>",
    "<ERROR_IDENTIFICADOR>",
    "<ERROR_IDENTIFICADOR_START_DIGIT>",
    "<ERROR_IDENTIFICADOR_MULTIPLE_UNDERSCORES>",
    "<ERROR_IDENTIFICADOR_START_LOWERCASE>",
    "<ERROR_IDENTIFICADOR_END_DIGIT>",
    "<ERROR_IDENTIFICADOR_START_UNDERSCORE>",
  };

}
